export const products = [
    { id: 13, name: "Organic Face Serum", price: 35.00, oldPrice: 50.00, rating: 4.9, image: "/images/face-serum.png", tag: "Natural", color: "bg-green-100 text-green-600", category: "beauty", description: "Revitalize your skin with our Organic Face Serum, crafted with 100% natural ingredients to boost hydration and reduce signs of aging." },
    { id: 14, name: "Matte Lipstick Set", price: 25.00, oldPrice: 40.00, rating: 4.8, image: "/images/lipstick-set.png", tag: "Hot", color: "bg-red-100 text-red-600", category: "beauty", description: "A collection of long-lasting, highly pigmented matte lipsticks in everyday shades." },
    { id: 15, name: "Perfume Collection", price: 80.00, oldPrice: 120.00, rating: 4.7, image: "/images/perfume-collection.png", tag: "Luxury", color: "bg-purple-100 text-purple-600", category: "beauty", description: "Experience luxury with our curated perfume collection, featuring exotic and timeless scents." },
    { id: 16, name: "Hydrating Moisturizer", price: 28.00, oldPrice: 35.00, rating: 4.6, image: "/images/moisturizer.png", tag: "Daily Use", color: "bg-blue-100 text-blue-600", category: "beauty", description: "Keep your skin soft and supple all day long with this lightweight, non-greasy hydrating moisturizer." },

    // Fashion - Women
    { id: 20, name: "Pink Elegance Anarkali", price: 120.00, oldPrice: 150.00, rating: 5.0, image: "/images/pink-dress.png", tag: "Bestseller", color: "bg-pink-100 text-pink-600", category: "fashion", description: "A stunning pink Anarkali suit perfect for festive occasions. Features intricate embroidery and a comfortable fit." },
    { id: 21, name: "Floral Summer Maxi", price: 55.00, oldPrice: 80.00, rating: 4.7, image: "/images/fashion-model.png", tag: "New", color: "bg-green-100 text-green-600", category: "fashion", description: "Breezy and beautiful, this floral maxi dress is your go-to outfit for summer brunches and beach walks." },
    { id: 22, name: "Classic Beige Coat", price: 180.00, oldPrice: 250.00, rating: 4.8, image: "/images/leather-bag.png", tag: "Premium", color: "bg-amber-100 text-amber-600", category: "fashion", description: "Timeless beige coat made from high-quality wool blend. Adds sophistication to any winter ensemble." },
    { id: 23, name: "Chic White Blouse", price: 45.00, oldPrice: 60.00, rating: 4.5, image: "/images/fashion-model.png", tag: "Essential", color: "bg-gray-100 text-gray-600", category: "fashion", description: "Versatile white blouse with lace details. Pairs perfectly with both trousers and skirts." },
    { id: 24, name: "Denim Jacket", price: 75.00, oldPrice: 95.00, rating: 4.6, image: "/images/leather-bag.png", tag: "Trending", color: "bg-blue-100 text-blue-600", category: "fashion", description: "A classic minimalist denim jacket that never goes out of style. Durable and stylish." },
    { id: 25, name: "Silk Evening Gown", price: 220.00, oldPrice: 300.00, rating: 4.9, image: "/images/pink-dress.png", tag: "Luxury", color: "bg-purple-100 text-purple-600", category: "fashion", description: "Elegant silk evening gown in deep red. Designed to make you stand out at any formal event." },
    { id: 26, name: "Casual Jumpsuit", price: 65.00, oldPrice: 85.00, rating: 4.4, image: "/images/fashion-model.png", tag: "Comfy", color: "bg-teal-100 text-teal-600", category: "fashion", description: "Comfortable and chic jumpsuit for everyday wear. Features adjustable waist and pockets." },
    { id: 27, name: "Boho Fringe Top", price: 40.00, oldPrice: 55.00, rating: 4.3, image: "/images/hero-fashion.png", tag: "Boho", color: "bg-orange-100 text-orange-600", category: "fashion", description: "Fun and playful fringe top. Great for festivals and casual outings." },
    // Home & Living
    { id: 3, name: "Premium Coffee Maker", price: 120.00, oldPrice: 150.00, rating: 4.7, image: "/images/coffee-maker.png", tag: "Best Seller", color: "bg-orange-100 text-orange-600", category: "home-living", description: "Brew the perfect cup every morning with this programmable premium coffee maker." },
    { id: 10, name: "Ceramic Vase Set", price: 40.00, oldPrice: 55.00, rating: 4.9, image: "/images/minimalist-decor.png", tag: "New", color: "bg-green-100 text-green-600", category: "home-living", description: "Minimalist ceramic vases that add elegance to any room. Perfect for fresh or dried flowers." },
    { id: 11, name: "Soft Throw Blanket", price: 35.00, oldPrice: 50.00, rating: 4.6, image: "/images/hero-home-living.png", tag: "Cozy", color: "bg-blue-100 text-blue-600", category: "home-living", description: "Ultra-soft throw blanket to keep you warm and cozy. available in multiple colors." },
    { id: 12, name: "Modern Desk Lamp", price: 65.00, oldPrice: 90.00, rating: 4.5, image: "/images/minimalist-decor.png", tag: "20% off", color: "bg-red-100 text-red-600", category: "home-living", description: "Sleek modern desk lamp with adjustable brightness. ideal for reading and work." },

    // Electronics
    { id: 1, name: "Wireless Headphones", price: 199.00, oldPrice: 250.00, rating: 4.8, image: "/images/wireless-headphones.png", tag: "20% off", color: "bg-blue-100 text-blue-600", category: "electronics", description: "Immersive sound quality with noise cancellation. Long battery life for all-day listening." },
    { id: 2, name: "Smart Watch Series 5", price: 299.00, oldPrice: 350.00, rating: 4.9, image: "/images/smart-watch.png", tag: "New", color: "bg-green-100 text-green-600", category: "electronics", description: "Track your fitness, heart rate, and notifications on the go with the new Series 5 Smart Watch." },
    { id: 5, name: "Bluetooth Speaker", price: 59.00, oldPrice: 80.00, rating: 4.5, image: "/images/bluetooth-speaker.png", tag: "Sale", color: "bg-purple-100 text-purple-600", category: "electronics", description: "Portable bluetooth speaker with punchy bass and waterproof design." },
    { id: 6, name: "Noise Cancelling Earbuds", price: 149.00, oldPrice: 199.00, rating: 4.7, image: "/images/earbuds.png", tag: "Hot", color: "bg-red-100 text-red-600", category: "electronics", description: "Compact earbuds with active noise cancellation and crystal clear call quality." },

    // New Electronics
    { id: 30, name: "Ultra HD 4K Smart TV", price: 899.00, oldPrice: 1200.00, rating: 4.8, image: "/images/hero-electronics.png", tag: "Best Seller", color: "bg-indigo-100 text-indigo-600", category: "electronics", description: "Experience cinematic visuals with this 55-inch Ultra HD 4K Smart TV. Built-in streaming apps included." },
    { id: 31, name: "Pro Gaming Laptop", price: 1499.00, oldPrice: 1800.00, rating: 4.9, image: "/images/hero-electronics.png", tag: "Performance", color: "bg-red-100 text-red-600", category: "electronics", description: "High-performance gaming laptop with latest dedicated graphics and high refresh rate screen." },
    { id: 32, name: "Smartphone 15 Pro", price: 999.00, oldPrice: 1099.00, rating: 4.9, image: "/images/smart-watch.png", tag: "Flagship", color: "bg-gray-100 text-gray-600", category: "electronics", description: "The ultimate smartphone experience with a stunning camera system and all-day battery life." },
    { id: 33, name: "Professional DSLR Camera", price: 2100.00, oldPrice: 2500.00, rating: 4.9, image: "/images/hero-electronics.png", tag: "Pro Choice", color: "bg-yellow-100 text-yellow-600", category: "electronics", description: "Capture life's moments in stunning detail with this professional-grade DSLR camera." },
    { id: 34, name: "10-inch Tablet", price: 349.00, oldPrice: 450.00, rating: 4.6, image: "/images/smart-watch.png", tag: "Portable", color: "bg-blue-100 text-blue-600", category: "electronics", description: "Versatile tablet perfect for work, play, and creativity on the go." },
    { id: 35, name: "Next-Gen Console", price: 499.00, oldPrice: 550.00, rating: 4.9, image: "/images/bluetooth-speaker.png", tag: "Gaming", color: "bg-neutral-100 text-neutral-600", category: "electronics", description: "Next-generation gaming console delivering 4K gaming at up to 120 FPS." },
    // Fashion - Others (Men/Unisex) from original Fashion file if any were missing
    { id: 4, name: "Leather Travel Bag", price: 85.00, oldPrice: 130.00, rating: 4.6, image: "/images/leather-bag.png", tag: "35% off", color: "bg-red-100 text-red-600", category: "fashion", description: "Durable leather travel bag with spacious compartments. Perfect for weekend getaways." },
    { id: 7, name: "Summer Floral Dress", price: 45.00, oldPrice: 60.00, rating: 4.8, image: "/images/pink-dress.png", tag: "New", color: "bg-green-100 text-green-600", category: "fashion", description: "Lightweight and airy floral dress for summer days." },
    { id: 8, name: "Classic Denim Jacket", price: 75.00, oldPrice: 95.00, rating: 4.7, image: "/images/leather-bag.png", tag: "Trending", color: "bg-blue-100 text-blue-600", category: "fashion", description: "Essential denim jacket for your wardrobe." },
    { id: 9, name: "Running Sneakers", price: 110.00, oldPrice: 150.00, rating: 4.5, image: "/images/leather-bag.png", tag: "Sale", color: "bg-orange-100 text-orange-600", category: "fashion", description: "Performance running sneakers with cushioned soles." },
];

export const reviews = [
    { id: 1, productId: 13, user: "Alice M.", rating: 5, comment: "Absolutely love this serum! My skin feels so soft.", date: "2023-10-12" },
    { id: 2, productId: 13, user: "Jessica K.", rating: 4, comment: "Great product, but the bottle is a bit small.", date: "2023-10-15" },
    { id: 3, productId: 14, user: "Sarah L.", rating: 5, comment: "The colors are amazing and stay on all day.", date: "2023-11-01" },
];
